---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  dependsOn:
    - name: sources
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1m
  path: ./clusters/components/infrastructure
  prune: true
  validation: client
