apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  timeout: 30m
  interval: 5m
  chart:
    spec:
      chart: tf-controller
      version: 0.2.5
      sourceRef:
        kind: HelmRepository
        name: tf-controller
        namespace: flux-system
      interval: 10m
